version: '2'

services:
  # Flask web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: python3 ./webapp/index.py
      - project_name=myproject
    volumes:
      - .:/root/myproject  # mount current directory inside container
    ports:
      - "5000:5000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - domain= [domain name]
        - port=[port] # Same as web port
    hostname: nginx
    command: ./setup-ssl.sh [domain name] [email]
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
